SistemaClinica/ClinicaWeb/Controllers/AccesoController.cs
using ClinicaEntidades;
using ClinicaWeb.Models.DTOs;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ClinicaData.Contrato;

namespace ClinicaWeb.Controllers
{
    public class AccesoController : Controller
    {
        private readonly IUsuarioRepositorio _repositorio;
        public AccesoController(IUsuarioRepositorio repositorio)
        {
            _repositorio = repositorio;
        }
        public IActionResult Login()
        {
            ClaimsPrincipal claimuser = HttpContext.User;
            if (claimuser.Identity!.IsAuthenticated)
            {
                string rol = claimuser.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).SingleOrDefault()!;
                if (rol == "Administrador") return RedirectToAction("Index", "Home");
                if (rol == "Paciente") return RedirectToAction("Index", "Citas");
                if (rol == "Doctor") return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(VMUsuarioLogin modelo)
        {
            if (modelo.DocumentoIdentidad == null || modelo.Clave == null)
            {
                ViewData["Mensaje"] = "No se encontraron coincidencias";
                return View();
            }

            Usuario usuario_encontrado = await _repositorio.Login(modelo.DocumentoIdentidad, modelo.Clave);

            if (usuario_encontrado == null)
            {
                ViewData["Mensaje"] = "No se encontraron coincidencias";
                return View();
            }

            ViewData["Mensaje"] = null;

            //aqui guarderemos la informacion de nuestro usuario
            List<Claim> claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, $"{usuario_encontrado.Nombre} {usuario_encontrado.Apellido}"),
                new Claim(ClaimTypes.NameIdentifier, usuario_encontrado.IdUsuario.ToString()),
                new Claim(ClaimTypes.Role,usuario_encontrado.RolUsuario.Nombre)
            };


            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);

            string rol = usuario_encontrado.RolUsuario.Nombre;
            if (rol == "Paciente") return RedirectToAction("Index", "Citas");
            if (rol == "Doctor") return RedirectToAction("CitasAsignadas", "Citas");

            return RedirectToAction("Index", "Home");
        }
        public IActionResult Registrarse()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Registrarse(VMPaciente modelo)
        {
            if (modelo.Clave != modelo.ConfirmarClave)
            {
                ViewBag.Mensaje = "Las contraseñas no coinciden";
                return View();
            }

            Usuario objeto = new Usuario()
            {
                NumeroDocumentoIdentidad = modelo.DocumentoIdentidad,
                Nombre = modelo.Nombre,
                Apellido = modelo.Apellido,
                Correo = modelo.Correo,
                Clave = modelo.Clave,
                RolUsuario = new RolUsuario()
                {
                    IdRolUsuario = 2
                }
            };
            string resultado = await _repositorio.Guardar(objeto);
            ViewBag.Mensaje = resultado;
            if (resultado == "")
            {
                ViewBag.Creado = true;
                ViewBag.Mensaje = "Su cuenta ha sido creada.";
            }
            return View();
        }

        public IActionResult Denegado()
        {
            return View();
        }
    }
}

SistemaClinica/ClinicaWeb/Views/Acceso/Denegado.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>404 Error - SB Admin</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="~/lib/fontawesome/all.js"></script>
</head>
<body>
    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <h1 class="display-1">401</h1>
                                <p class="lead">Unauthorized</p>
                                <p>No tiene acceso a esta página.</p>
                                @if (User.IsInRole("Administrador"))
                                {
                                    <a asp-controller="Home" asp-action="Index">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        regresar a Dashboard
                                    </a>
                                }
                                else if (User.IsInRole("Paciente"))
                                {
                                    <a asp-controller="Citas" asp-action="Index">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        regresar a Citas
                                    </a>
                                }else if (User.IsInRole("Doctor"))
                                {
                                    <a asp-controller="Citas" asp-action="CitasAsignadas">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        regresar a Citas
                                    </a>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutError_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/scripts.js"></script>
</body>
</html>

SistemaClinica/ClinicaWeb/Views/Acceso/Login.cshtml
@model ClinicaWeb.Models.DTOs.VMUsuarioLogin;
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login - SB Admin</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="~/lib/fontawesome/all.js"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                <div class="card-body">
                                    
                                    <form asp-controller="Acceso" asp-action="Login" method="post">
                                        <div class="form-floating mb-3">
                                            <input class="form-control" type="text" placeholder="Nro Documento" asp-for="DocumentoIdentidad" required />
                                            <label for="inputEmail">Nro Documento</label>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" type="password" placeholder="Contraseña" asp-for="Clave" required />
                                            <label for="inputPassword">Contraseña</label>
                                        </div>
                                        @if (ViewData["Mensaje"] != null)
                                        {
                                            <div class="form-group">
                                                <div class="alert alert-danger" role="alert">
                                                    @ViewData["Mensaje"]
                                                </div>
                                            </div>
                                        }

                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                                        </div>
                                    </form>

                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a asp-controller="Acceso" asp-action="Registrarse">Necesitas una cuenta? Registrate!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/scripts.js"></script>
</body>
</html>

SistemaClinica/ClinicaWeb/Views/Acceso/Registrarse.cshtml
@model ClinicaWeb.Models.DTOs.VMPaciente;
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Registrarse - Clinica</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="~/lib/fontawesome/all.js"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Crear Cuenta</h3></div>
                                <div class="card-body">
                                    @if (ViewBag.Creado == null)
                                    {
                                        <form asp-controller="Acceso" asp-action="Registrarse" method="post">
                                            <div class="row mb-3">
                                                <div class="col-md-6">
                                                    <div class="form-floating mb-3 mb-md-0">
                                                        <input class="form-control" type="text" placeholder="Enter your first name" asp-for="DocumentoIdentidad" />
                                                        <label for="inputFirstName">Nro. Documento</label>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-floating">
                                                        <input class="form-control" type="text" placeholder="Enter your last name" asp-for="Nombre" />
                                                        <label for="inputLastName">Nombres</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row mb-3">
                                                <div class="col-md-6">
                                                    <div class="form-floating mb-3 mb-md-0">
                                                        <input class="form-control" type="text" placeholder="Enter your first name" asp-for="Apellido" />
                                                        <label for="inputFirstName">Apellidos</label>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-floating">
                                                        <input class="form-control" type="email" placeholder="Enter your last name" asp-for="Correo" />
                                                        <label for="inputLastName">Correo</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row mb-3">
                                                <div class="col-md-6">
                                                    <div class="form-floating mb-3 mb-md-0">
                                                        <input class="form-control" type="password" placeholder="Create a password" asp-for="Clave" />
                                                        <label for="inputPassword">Contraseña</label>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-floating mb-3 mb-md-0">
                                                        <input class="form-control" type="password" placeholder="Confirm password" asp-for="ConfirmarClave" />
                                                        <label for="inputPasswordConfirm">Confirmar Contraseña</label>
                                                    </div>
                                                </div>
                                            </div>
                                            @if (ViewBag.Mensaje != null)
                                            {
                                                <div class="alert alert-danger">
                                                    @ViewBag.Mensaje
                                                </div>
                                            }
                                            <div class="mt-4 mb-0">
                                                <div class="d-grid"><button class="btn btn-primary btn-block" type="submit">Crear Cuenta</button></div>
                                            </div>
                                        </form>
                                    }else{
                                        <div class="alert alert-success">
                                            <p>@ViewBag.Mensaje</p>
                                        </div>
                                    }
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a asp-controller="Acceso" asp-action="Login">Ya tienes una cuenta? Acceder</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/scripts.js"></script>
</body>
</html>