SistemaClinica/ClinicaWeb/Controllers/CitasController.cs
using ClinicaData.Contrato;
using ClinicaEntidades;
using ClinicaEntidades.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ClinicaWeb.Controllers
{
    public class CitasController : Controller
    {
        private readonly IDoctorRepositorio _repositorio;
        private readonly ICitaRepositorio _repositorioCita;
        public CitasController(IDoctorRepositorio repositorio, ICitaRepositorio repositorioCita)
        {
            _repositorio = repositorio;
            _repositorioCita = repositorioCita;
        }
        [Authorize(Roles = "Paciente")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Paciente")]
        public IActionResult NuevaCita()
        {
            return View();
        }

        [Authorize(Roles = "Doctor")]
        public IActionResult CitasAsignadas()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ListaDoctorHorarioDetalle(int Id)
        {
            List<FechaAtencionDTO> lista = await _repositorio.ListaDoctorHorarioDetalle(Id);
            return StatusCode(StatusCodes.Status200OK, new { data = lista });
        }

        [HttpPost]
        public async Task<IActionResult> Guardar([FromBody] Cita objeto)
        {

            ClaimsPrincipal claimuser = HttpContext.User;
            string idUsuario = claimuser.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).SingleOrDefault()!;

            objeto.Usuario = new Usuario
            {
                IdUsuario = int.Parse(idUsuario)
            };

            string respuesta = await _repositorioCita.Guardar(objeto);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

        [HttpGet]
        public async Task<IActionResult> ListaCitasPendiente()
        {
            ClaimsPrincipal claimuser = HttpContext.User;
            string idUsuario = claimuser.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).SingleOrDefault()!;

            List<Cita> lista = await _repositorioCita.ListaCitasPendiente(int.Parse(idUsuario));
            return StatusCode(StatusCodes.Status200OK, new { data = lista });
        }

        [HttpDelete]
        public async Task<IActionResult> Cancelar(int Id)
        {
            string respuesta = await _repositorioCita.Cancelar(Id);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

       
    }
}

SistemaClinica/ClinicaWeb/Controllers/DoctorHorarioController.cs
using ClinicaData.Contrato;
using ClinicaEntidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ClinicaWeb.Controllers
{
    public class DoctorHorarioController : Controller
    {
        private readonly IDoctorRepositorio _repositorio;
        public DoctorHorarioController(IDoctorRepositorio repositorio)
        {
            _repositorio = repositorio;
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<DoctorHorario> lista = await _repositorio.ListaDoctorHorario();
            return StatusCode(StatusCodes.Status200OK, new { data = lista });
        }


        public async Task<IActionResult> Guardar([FromBody] DoctorHorario objeto)
        {
            string respuesta = await _repositorio.RegistrarHorario(objeto);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int Id)
        {
            string respuesta = await _repositorio.EliminarHorario(Id);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

    }
}

SistemaClinica/ClinicaWeb/Controllers/EspecialidadController.cs
using ClinicaData.Contrato;
using ClinicaEntidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ClinicaWeb.Controllers
{
    public class EspecialidadController : Controller
    {
        private readonly IEspecialidadRepositorio _repositorio;
        public EspecialidadController(IEspecialidadRepositorio repositorio)
        {
            _repositorio = repositorio;
        }

        [Authorize(Roles = "Administrador")]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<Especialidad> lista = await _repositorio.Lista();
            return StatusCode(StatusCodes.Status200OK, new { data = lista });
        }

        public async Task<IActionResult> Guardar([FromBody] Especialidad objeto)
        {
            string respuesta = await _repositorio.Guardar(objeto);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

        [HttpPut]
        public async Task<IActionResult> Editar([FromBody] Especialidad objeto)
        {
            string respuesta = await _repositorio.Editar(objeto);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int Id)
        {
            int respuesta = await _repositorio.Eliminar(Id);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }
    }
}

SistemaClinica/ClinicaWeb/Controllers/UsuarioController.cs
using ClinicaData.Contrato;
using ClinicaEntidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ClinicaWeb.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _repositorio;
        public UsuarioController(IUsuarioRepositorio repositorio)
        {
            _repositorio = repositorio;
        }
        
        [Authorize(Roles = "Administrador")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<Usuario> lista = await _repositorio.Lista(1);
            return StatusCode(StatusCodes.Status200OK, new { data = lista });
        }

        [HttpPost]
        public async Task<IActionResult> Guardar([FromBody] Usuario objeto)
        {
            string respuesta = await _repositorio.Guardar(objeto);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

        [HttpPut]
        public async Task<IActionResult> Editar([FromBody] Usuario objeto)
        {
            string respuesta = await _repositorio.Editar(objeto);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int Id)
        {
            int respuesta = await _repositorio.Eliminar(Id);
            return StatusCode(StatusCodes.Status200OK, new { data = respuesta });
        }
    }
}

SistemaClinica/ClinicaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clinica - Net8</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    @RenderSection("Estilos", required: false)
    <script src="~/lib/fontawesome/all.js"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="#">Clinica</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            @*  <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div> *@
        </form>
        <!-- Navbar-->
        @await Component.InvokeAsync("MenuUsuario")
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        @if (User.IsInRole("Administrador"))
                        {
                            <a class="nav-link" asp-controller="Home" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                        }
                        
                        <div class="sb-sidenav-menu-heading">Gestion</div>
                        @if (User.IsInRole("Administrador"))
                        {
                            <a class="nav-link" asp-controller="Usuario" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Usuario
                            </a>
                            <a class="nav-link" asp-controller="Especialidad" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Especialidad
                            </a>
                            <a class="nav-link" asp-controller="Doctor" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Doctor
                            </a>
                            <a class="nav-link" asp-controller="DoctorHorario" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Doctor Horario
                            </a>
                        }
                        @if (User.IsInRole("Paciente"))
                        {
                            <a class="nav-link" asp-controller="Citas" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Mis Citas
                            </a>
                            <a class="nav-link" asp-controller="HistorialCitas" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Historial Citas
                            </a>
                        }

                        @if (User.IsInRole("Doctor"))
                        {
                            <a class="nav-link" asp-controller="Citas" asp-action="CitasAsignadas">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Citas
                            </a>
                        }

                        
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/lib/sweetalert2/js/sweetalert2.js"></script>
    <script src="~/lib/loadingoverlay/loadingoverlay.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>